services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leads-process-api
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - .env
